Repository bookSailer/functionalProgramming, pull requests merged in 2024-07, with the labels that each got.

#78 [bookSailor/functionalProgramming] chapter13_최기환
  chapter_13/README.md
Labels: chapter13

#77 [bookSailor/functionalProgramming] chapter13_강수영
  chapter_13/README.md
Labels: chapter13

#76 [bookSailer/functionalCoding] chapter8_문수정
  chapter_08/README.md
Labels: chapter8

#75 [bookSailor/functionalProgramming] chapter10_문선주
  chapter_10/README.md
Labels: chapter10

#83 [bookSailor/functionalProgramming] chapter14_우신애
  chapter_14/README.md
Labels: chapter14

#84 [bookSailor/functionalProgramming] chapter9_문수정
  chapter_09/README.md
Labels: chapter9

#82 [bookSailor/functionalProgramming] chapter14_최기환
  chapter_14/README.md
Labels: chapter14

#81 [bookSailor/functionalProgramming] chapter14_김지나
  chapter_14/README.md
Labels: chapter14

#80 [bookSailor/functionalProgramming] chapter13_김지나
  chapter_13/README.md
Labels: chapter13

#79 [bookSailor/functionalProgramming] chapter13_우신애
  chapter_13/README.md
Labels: chapter13

#85 [bookSailor/functionalProgramming] chapter15_최기환
  chapter_15/README.md
Labels: chapter15

#87 [bookSailor/functionalProgramming] chapter14,15_강수영
  chapter_14/README.md
  chapter_15/README.md
Labels: chapter14, chapter15

#88 [bookSailor/functionalProgramming] chapter15_김지나
  chapter_15/README.md
Labels: chapter15

#86 [bookSailor/functionalProgramming] chapter15_우신애
  chapter_15/README.md
Labels: chapter15

#89 [bookSailor/functionalProgramming] chapter16_우신애
  chapter_16/README.md
Labels: chapter16

#90 [bookSailor/functionalProgramming] chapter16_김지나
  chapter_16/README.md
Labels: chapter16

#91 [bookSailor/functionalProgramming] chapter16_최기환
  chapter_16/README.md
Labels: chapter16
