Repository bookSailer/functionalProgramming, pull requests merged in 2024-08, with the labels that each got.

#92 [bookSailor/functionalProgramming] chapter17_최기환
  chapter_17/README.md
Labels: chapter17

#93 [bookSailor/functionalProgramming] chapter17_우신애
  chapter_17/README.md
Labels: chapter17

#94 [bookSailor/functionalProgramming] chapter16, 17_강수영
  chapter_16/README.md
  chapter_17/README.md
Labels: chapter16, chapter17

#99 [bookSailor/functionalProgramming] chapter18, 19_강수영
  chapter_18/README.md
  chapter_19/README.md
Labels: chapter18, chapter19

#98 [bookSailor/functionalProgramming] chapter18_김지나
  chapter_18/README.md
Labels: chapter18

#97 [bookSailor/functionalProgramming] chapter18_우신애
  chapter_18/README.md
Labels: chapter18

#96 [bookSailor/functionalProgramming] chapter18_최기환
  chapter_18/README.md
Labels: chapter18
