Repository bookSailer/functionalProgramming, pull requests merged in 2024-05, with the labels that each got.

#25 [bookSailer/functionalCoding] chap4_최기환
  chapter_04/README.md
Labels: chapter4

#26 [bookSailer/functionalCoding] chap4_강수영
  chapter_04/README.md
Labels: chapter4

#27 [bookSailer/functionalCoding] chap4_우신애
  chapter_04/README.md
Labels: chapter4

#28 [bookSailer/functionalCoding] chap4_김지나
  chapter_04/README.md
Labels: chapter4

#29 [bookSailer/functionalCoding] chap4_문선주
  chapter_04/README.md
Labels: chapter4

#30 chapter4_이정아
  chapter_04/README.md
Labels: chapter4

#34 [bookSailer/functionalCoding] chap5_우신애
  chapter_05/README.md
Labels: chapter5

#33 [bookSailer/functionalCoding] chap5_김지나
  chapter_05/README.md
Labels: chapter5

#32 [bookSailer/functionalCoding] chapter5_최기환
  chapter_05/README.md
Labels: chapter5

#31 [bookSailer/functionalCoding] chap5_강수영
  chapter_05/README.md
Labels: chapter5

#39 [bookSailer/functionalCoding] chap6_문선주
  chapter_06/README.md
Labels: chapter6

#38 [bookSailer/functionalCoding] chap5_문선주
  chapter_05/README.md
Labels: chapter5

#36 feat: chapter6_최기환
  chapter_06/README.md
Labels: chapter6

#37 [bookSailer/functionalCoding] chap6_김지나
  chapter_06/README.md
Labels: chapter6

#41 [bookSailer/functionalCoding] chap6_우신애
  chapter_06/README.md
Labels: chapter6

#46 [bookSailer/functionalCoding] chap7_강수영
  chapter_07/README.md
Labels: chapter7

#42 chapter6_이정아
  chapter_06/README.md
Labels: chapter6

#49 [bookSailer/functionalCoding] chap7_우신애
  chapter_07/README.md
Labels: chapter7

#43 [bookSailer/functionalCoding] chap7_김지나
  chapter_07/README.md
Labels: chapter7

#48 [bookSailer/functionalCoding] chap7_최기환
  chapter_07/README.md
Labels: chapter7

#52 [bookSailer/functionalCoding] chap8_우신애
  chapter_08/README.md
Labels: chapter8

#51 [bookSailer/functionalCoding] chap8_강수영
  chapter_08/README.md
Labels: chapter8

#50 [bookSailer/functionalCoding] chap8_김지나
  chapter_08/README.md
Labels: chapter8
