Repository bookSailer/functionalProgramming, pull requests merged in 2024-04, with the labels that each got.

#11 [bookSailer/functionalCoding] chap1_우신애
  chapter_01/README.md
Labels: chapter1

#7 [bookSailer/functionalCoding] chap1_강수영
  .idea/.gitignore
  .idea/functionalProgramming.iml
  .idea/modules.xml
  .idea/vcs.xml
  chapter_01/README.md
Labels: chapter1

#5 [bookSailer/functionalCoding] chap1_문선주
  chapter_01/README.md
Labels: chapter1

#2 [bookSailer/functionalCoding] chap1_최기환
  chapter_01/README.md
Labels: chapter1

#12 [bookSailer/functionalCoding] chap2_우신애
  chapter_02/README.md
Labels: chapter2

#10 [bookSailer/functionalCoding] chap2_김지나
  chapter_02/README.md
Labels: chapter2

#6 [bookSailer/functionalCoding] chap2_문선주
  chapter_02/README.md
Labels: chapter2

#3 [bookSailer/functionalCoding] chap2_최기환
  chapter_02/README.md
Labels: chapter2

#13 [bookSailer/functionalCoding] chapter1_문수정
  chapter_01/README.md
Labels: chapter1

#14 [bookSailer/functionalCoding] chapter2_문수정
  chapter_02/README.md
Labels: chapter2

#17 [bookSailer/functionalCoding] chapter2_이정아
  chapter_02/README.md
Labels: chapter2

#18 chapt3_강수영
  chapter_03/README.md
Labels: chapter3

#19 chapt3_김지나
  chapter_03/README.md
Labels: chapter3

#20 [bookSailer/functionalCoding] chap3_최기환
  chapter_03/README.md
Labels: chapter3

#21 [bookSailer/functionalCoding] chap3_우신애
  chapter_03/README.md
Labels: chapter3

#22 [bookSailer/functionalCoding] chap3_문수정
  chapter_03/README.md
Labels: chapter3

#23 [bookSailer/functionalCoding] chap3_문선주
  chapter_03/README.md
Labels: chapter3

#24 [bookSailer/functionalCoding] chapter3_이정아
  chapter_03/README.md
Labels: chapter3
